sudo: required
language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt coverageReport coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- pip install --user codecov
- sudo chmod +x /usr/local/bin/sbt
after_success:
- codecov
