sudo: required
language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt coverageReport coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $R_LIBS_USER
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base
      - r-recommended
before_install:
- pip install --user codecov
- Rscript -e 'if (!require("ggplot2", quietly=T)) install.packages("ggplot2", lib=Sys.getenv("R_LIBS_USER"), repos="http://cran.us.r-project.org", dependencies=TRUE)'
- sudo chmod +x /usr/local/bin/sbt
after_success:
- codecov
env:
  global:
  - R_LIBS_USER=$HOME/Rlib
