coverage:
  branch: devel
  ignore:
  - .*com/fulcrumgenomics/str/pipelines/.*
  - .*com/fulcrumgenomics/str/tasks/.*
  - .*com/fulcrumgenomics/str/cmdline/FgStrMain.scala
  status:
    patch:
      default:
        target: '80'
    project:
      default:
        target: auto
